language: android

env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.3

android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
  
jdk:
- oraclejdk8

script: "./gradlew clean test build --stacktrace"

branches:
  except:
  - images
  - gh-pages
  
notifications:
  email: false
  slack:
    rooms: jahirfiquitiva:StCMaxV85iad38DdSMBY43xW
    template:
    - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}: ''%{commit_subject}''>)  by
      %{author} for %{repository_name}@%{branch}, %{result} in %{duration}. <%{build_url}|Check
      details>.'
      
sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_script:
- chmod +x gradlew

before_install:
- yes | sdkmanager "platforms;android-27"

deploy:
  provider: releases
  api_key:
    secure: 3OjMyDi9Hm1D5MR/uhjvLvQhjA7xk/HORLnGwrs4vfBLXKfiVIVcHFLRFmTgkWu2Y9zAtUxmU9Q4LQk5dvGeM++CN73DFVTgFf0+a/bOP3YHER4Fz7LmV4GDtpVgavVlN80tIoycMmmh9YU+GCR9MxpsSWHG8ng/Bv8y1/0S/rknJJIbe7SeZijaTJEzGu73XKDNwvtk7HBDRgwJKl+ZFxqtIFPBBsHfmS2aG0nqjkWsa8tV4Y94BmwvcK7Pe3SZR5JAhi/hTSr1ihW2qFU0Di1lfpJljOxTUbcrZJD3BN6eKbT906ebkR/wQZMFcr+5pQlUqoTzeC8tJH+EAhwQZuhj6y0DALsXdqw7RSNptf6pExIJ+3iVpaiV/pXl6qYHgnnacOVwXVbsRzNHy9T2fey8upBQUTsPl4fG15KbBr9BkN8nG/ajdvWNSvEP4S/B4AAk5dn13w+0/QGkNvA0sKul10jBnheMTIUY7Z6fdHEgDkvpclbzeEtvi8RDFjn9Wbpibn1jgFHJEiiWYJ8U3rWPLTYnFknWMx0C6Krpwt9zFxMBjZon5KH+0jZZFQ4eqKSIi51z78hokD0OevA/v34zSoIxv/LNHIIEai/L/fXBK0JivWVHUoc5hOXDdqx7+qppY4JpIqkyZfJEYT+N/2a7Is6dcyoQ7J+HW6ySVGQ=
  file_glob: true
  file: 
    - $HOME/app/build/outputs/apk/debug/*.apk
    - $HOME/app/build/outputs/apk/*/*.apk
    - '*/app/build/outputs/apk/debug/*.apk'
    - /app/build/outputs/apk/debug/*.apk
    - app/build/outputs/apk/debug/*.apk
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    repo: jahirfiquitiva/Frames
    tags: true
